torontodata <- read_csv("C:/Users/jacob/Documents/HighVisCrosswalks/Toronto/Products/TorontoCrosswalkwithCrashesVehiclePed2.csv")
torontodata2 <- torontodata |> filter(TYPECHANGESIMPLE=="Low-to-High-Vis")
mean_change <- mean(torontodata2$CrashChange, na.rm = TRUE)
ggplot(torontodata2,aes(x=CrashChange))+geom_bar()+geom_vline(aes(xintercept=mean_change))+labs(title="Difference of 4-year Crash Totals", subtitle="Before and After High-Visibility Crosswalk Treatment",x="Difference in Crash Totals", y="Frequency") 
ggsave("C:/Users/jacob/Documents/HighVisCrosswalks/Toronto/Products/crashchangedensity.png")
torontodata3 <- torontodata2 |> mutate(CrashRateBefore=CrashesBefore/PedsBefore,CrashRateAfter=CrashesAfter/PedsAfter,CrashRateChange=CrashRateAfter-CrashRateBefore, .keep="used")
torontodata3 |> summarise(CrashRateChangeMean = mean(CrashRateChange))
mean_ratechange <- mean(torontodata3$CrashRateChange, na.rm = TRUE)
ggplot(torontodata3,aes(x=CrashRateChange))+geom_histogram(binwidth=0.001)+geom_vline(aes(xintercept=mean_ratechange))+labs(title="Difference of 4-year Crash Rate", subtitle="Before and After High-Visibility Crosswalk Treatment",x="Difference in Crash Rate", y="Frequency")
ggsave("C:/Users/jacob/Documents/HighVisCrosswalks/Toronto/Products/crashratedensity.png")